### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by GamesOpenSource** [cvincent/elite-command#2]
Hello, I intend to upload the fantastic art of this game to opengameart, in hopes that open source games will profit from it!

Looking at the achievements art, I noticed that the style looks different from the rest of the game. Because of this, I would like clarification: are there any art assets in `elite-command-master/public/images/` that are not CC-BY 4.0 licensed - perhaps any were taken from some free art website or something like that? Thanks!

**Comment by cvincent** [comment]
All art in the game was commissioned specifically for the game and falls under the same license as the rest of the source. Go for it!

**Comment by unstoppablecarl** [comment]
Who did the graphics? Looks like they were done in 3d. Are the 3d files available somewhere?
